version: "3"
services:
  backend:
    build:
      context: ./microservice-funiber-inventario
      dockerfile: Dockerfile
    networks:
      - funiber_inventory_network
    ports:
      - "8000:8000"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/funiber_inventory?allowPublicKeyRetrieval=true
    env_file:
      - ./microservice-funiber-inventario/.env
    depends_on:
      - mysqldb
  frontend:
    build:
      context: ./funiber-inventory-nextjs
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./funiber-inventory-nextjs/.env.local

  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3306:3306
    networks:
      - funiber_inventory_network
    environment:
      MYSQL_DATABASE: funiber_inventory
      MYSQL_USER: root
      MYSQL_PASSWORD: root123
      MYSQL_ROOT_PASSWORD: root123

networks:
  funiber_inventory_network:
